[workspace]
members = [
  # core
  "leptos",
  "leptos_dom",
  "leptos_config",
  "leptos_macro",
  "leptos_reactive",
  "leptos_server",

  # integrations
  "integrations/actix",
  "integrations/axum",

  # libraries
  "meta",
  "router",

  # book
  "docs/book/project/ch02_getting_started",
  "docs/book/project/ch03_building_ui",
  "docs/book/project/ch04_reactivity",
]
exclude = ["benchmarks", "examples"]

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[workspace.metadata.cargo-all-features]
skip_feature_sets = [["csr", "ssr"], ["csr", "hydrate"], ["ssr", "hydrate"]]