[package]
name = "leptos_actix"
version = "0.1.0-beta"
edition = "2021"
authors = ["Greg Johnston"]
license = "MIT"
repository = "https://github.com/gbj/leptos"
description = "Actix integrations for the Leptos web framework."

[dependencies]
actix-web = "4"
futures = "0.3"
leptos = { path = "../../leptos", default-features = false, version = "0.1.0-alpha", features = [
	"ssr",
] }
leptos_meta = { path = "../../meta", default-features = false, version = "0.1.0-alpha", features = [
	"ssr",
] }
leptos_router = { path = "../../router", default-features = false, version = "0.1.0-alpha", features = [
	"ssr",
] }
tokio = { version = "1.0", features = ["full"] }
